### ISSUE TITLE
rrdiagrams JavaScript version problems

### ISSUE THREAD

**Issue by ThosG** [Chrriis/rrdiagram-js#1]
Tried to set up the JS version. Presumably the 'src' file is meant to be imported as a module? I get the response

Access to script at 'file:///...../src/ui/rrdiagram.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

I don't understand about JS modules yet. Can you give a fully described explanation of how to include your code in my page? I would be very grateful.

**Comment by Chrriis** [comment]
Hi,
I load these source files in VS code, but I build the JS file and use that result in web pages.

The simplest is to get the `rrdiagram.js` file from the [releases page](https://github.com/Chrriis/rrdiagram-js/releases) and integrate it in your page.

Check the sources of this unofficial test page:
http://nextencia.net/rrdiagram-js/RRDiagramJSTest.html

Hope this helps,
-Christopher
